# Generated by Django 3.2.10 on 2022-01-26 14:00

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('description', models.TextField(max_length=400, verbose_name='Descripción')),
                ('main_image', models.ImageField(upload_to='articles/main', verbose_name='Imagen Principal')),
                ('main_image_opt_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto alt. Principal')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='articles/optional', verbose_name='Imagen 2')),
                ('image_1_opt_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto alt. 2')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='articles/optional', verbose_name='Imagen 3')),
                ('image_2_opt_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto alt. 3')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='articles/optional', verbose_name='Imagen 4')),
                ('image_3_opt_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto alt. 4')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='articles/optional', verbose_name='Imagen 5')),
                ('image_4_opt_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto alt. 5')),
                ('is_active', models.BooleanField(default=True)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Oferta Inicial')),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Oferta Actual')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
            managers=[
                ('article_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
