# Generated by Django 3.2.10 on 2022-01-06 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto')),
                ('description', models.CharField(max_length=130, verbose_name='Descripción')),
                ('payment_type', models.CharField(choices=[('0', 'TARJETA'), ('1', 'DEPOSITO'), ('2', 'CONTRAENTREGA')], default=0, max_length=25, verbose_name='Tipo de Pago')),
                ('status_payment', models.CharField(blank=True, choices=[('0', 'Pendiente'), ('1', 'Pagado')], max_length=25, null=True, verbose_name='Estado del Pago')),
                ('date_payment', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_pago', to='article.article')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
